"use client";
import { UserProvider } from "@/context/userContext";
import "./globals.css";
import "animate.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-full">
        <UserProvider>{children}</UserProvider>
        <script
          src="https://unpkg.com/@dotlottie/player-component@2.7.12/dist/dotlottie-player.mjs"
          type="module"
        ></script>
      </body>
    </html>
  );
}
