export const users = [
  {
    id: 1,
    name: "Tony Reichert",
    email: "tony.reichert@example.com",
    status: "active",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/1.png",
  },
  {
    id: 2,
    name: "Zoey Lang",
    email: "zoey.lang@example.com",
    status: "paused",
    age: "25",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/1.png",
  },
  {
    id: 3,
    name: "Jane Fisher",
    email: "jane.fisher@example.com",
    status: "active",
    age: "22",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/2.png",
  },
  {
    id: 4,
    name: "William Howard",
    email: "william.howard@example.com",
    status: "vacation",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/2.png",
  },
  {
    id: 5,
    name: "Kristen Copper",
    email: "kristen.cooper@example.com",
    status: "active",
    age: "24",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/3.png",
  },
  {
    id: 6,
    email: "brian.kim@example.com",
    name: "Brian Kim",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/3.png",
    status: "active",
  },
  {
    id: 7,
    name: "Michael Hunt",
    email: "michael.hunt@example.com",
    status: "paused",
    age: "27",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/4.png",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    email: "samantha.brooks@example.com",
    status: "active",
    age: "31",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/4.png",
  },
  {
    id: 9,
    name: "Frank Harrison",
    email: "frank.harrison@example.com",
    status: "vacation",
    age: "33",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/5.png",
  },
  {
    id: 10,
    name: "Emma Adams",
    email: "emma.adams@example.com",
    status: "active",
    age: "35",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/5.png",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    email: "brandon.stevens@example.com",
    status: "active",
    age: "22",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/7.png",
  },
  {
    id: 12,
    name: "Megan Richards",
    email: "megan.richards@example.com",
    status: "paused",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/7.png",
  },
  {
    id: 13,
    name: "Oliver Scott",
    email: "oliver.scott@example.com",
    status: "active",
    age: "37",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/8.png",
  },
  {
    id: 14,
    name: "Grace Allen",
    email: "grace.allen@example.com",
    status: "active",
    age: "30",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/8.png",
  },
  {
    id: 15,
    name: "Noah Carter",
    email: "noah.carter@example.com",
    status: "paused",
    age: "31",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/9.png",
  },
  {
    id: 16,
    name: "Ava Perez",
    email: "ava.perez@example.com",
    status: "active",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/9.png",
  },
  {
    id: 17,
    name: "Liam Johnson",
    email: "liam.johnson@example.com",
    status: "active",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    email: "sophia.taylor@example.com",
    status: "active",
    age: "27",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/11.png",
  },
  {
    id: 19,
    name: "Lucas Harris",
    email: "lucas.harris@example.com",
    status: "paused",
    age: "32",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/12.png",
  },
  {
    id: 20,
    name: "Mia Robinson",
    email: "mia.robinson@example.com",
    status: "active",
    age: "26",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png",
  },
];
